### ISSUE TITLE
Update Firmware device console output is inconsistent

### ISSUE THREAD

**Issue by lamebrain** [WildernessLabs/Netduino-Updater#13] opened 2018-04-03 14:34 UTC
When clicking on "Update Firmware" the progress output in the device console doesn't make sense.

<img width="245" alt="device_console" src="https://user-images.githubusercontent.com/1048330/38255707-62bdc3d0-3711-11e8-9a48-a8651ad4e986.PNG">

**Comment by adrianstevens** [comment] 2018-04-07 20:44
@lamebrain which device are you updating? 

The "Update Complete" bug is an easy fix but I haven't been able to repro the inconsistant percentages. I'll dig through the code anyways and see if I can spot a potential math error.

**Comment by adrianstevens** [comment] 2018-04-07 20:56
I've got a quick hack in the code to ensure it never reports over 100% - but it means that somehow the amount of data being reported during the update is exceeding the expected total amount

**Comment by adrianstevens** [comment] 2018-04-14 20:46
I've tested v2.0.2 with an N3, N3E, N3WiFi, and N2 and can't reproduce so I'm confident this is fixed - closing issue

**Closed by adrianstevens** 2018-04-14 20:46 UTC
